---
abstract: 'Translate content with the Internationalizationizer'
author:
  - "Marty O'Brien, C<< <mob at cpan.org> >>"
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: I22r-Translate
no_index:
  directory:
    - inc
    - t
  package:
    - I22r::Translate::Request
    - I22r::Translate::Result
    - I22r::REST::Google
    - I22r::REST::Google::Translate
    - I22r::REST::Google::Data
requires:
  Class::Accessor: 0
  Class::Data::Inheritable: 0
  HTTP::Request: 0
  JSON::Any: 0
  LWP::UserAgent: 0
  Moose: 0
  Moose::Role: 0
  MooseX::ClassAttribute: 0
  URI: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.94
